### ISSUE TITLE
How to compile examples?

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ngagesdk/ngage-toolchain#10]
hey yall, so anyways i want to compile the test applications for the ngagesdk but idk how to compile the apps, so can you help me please.

**Comment by mupfdev** [comment]
Check out the new SDL2 example application. The README explains the process in great detail.

https://github.com/ngagesdk/SDLexample

**Comment by JohnnyZig** [comment]
That link 404-ed. Is there some new example in the repo?
