### ISSUE TITLE
How To create a cmake file for ngagesdk?

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ngagesdk/ngage-toolchain#11]
hey guys so anyways, i was trying to create my own cmake file via the sdl2 cmakelists.txt file but here's the problem when i try to compile it in visual studio 2022, it gives me a 404 error, idk what to do anymore so can you help me get it compiling?

**Comment by mupfdev** [comment]
Due to recent changes in the toolchain, I suggest you to install it from scratch. Then use wordle or ccleste as a reference.
