### ISSUE TITLE
How To compile test apps?

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ngagesdk/ngage-toolchain#2]
hey, so anyways i installed the ngagesdk and all that jazz but how do i compile the examples and run them on ngage hardware? Because I want to compile the example test applications.

**Comment by mupfdev** [comment]
There's only one demo application right now.

https://github.com/ngagesdk/SDL-1.2

Just follow the instructions and open the resulting .exe file using FExplorer.

**Comment by NeoGeoFreak2004** [comment]
but here is the thing, when i type cmake . into the terminal it gives me an error, the error says CMake generate step failed, or something like that.

**Comment by mupfdev** [comment]
Try to follow my instructions as closely as possible, from setting up the SDK to compiling the demo application.

If there are still problems, describe the exact problem in as much detail as possible. Otherwise, I'm afraid I can't help you any further.
