### ISSUE TITLE
Path Issue

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ngagesdk/ngage-toolchain#4]
Hey yall, so anyways i did the git clone to the ngage-toolchain and it went well but when i cd to the root directory then changed directories in the projects folder and it went great. but then I had a issue, when i type in cmake . it gives me a error, the error says "CMake Error at CMakeLists.txt:6 (message):
  The environment variable NGAGESDK needs to be defined."
IDK what to do about this error, how do I set the path to the ngage-toolchan for the sdk!

**Comment by ngagesdk** [comment]
It is explained in the README.md.
You have to set/create the Windows environment variate NGAGESDK as specified.
