### ISSUE TITLE
Path environment set?

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ngagesdk/ngage-toolchain#6]
Hey yall, so anyways i am just wondering, how do i set the path environment on visual studio 2022 for the ngagesdk. because i just git cloned the repository and it worked out well. but i got confused when it told me to create a new path enviorment variable and yes, i read the tutorial line to line, but anyways how do i set the environment on visual studio 2022 with the ngagesdk!

**Comment by mupfdev** [comment]
This is something you do for Windows, not for Visual Studio.

**Comment by NeoGeoFreak2004** [comment]
but Here is the thing I set the path environment to C:/ngage-toolchain, and it still gives me the path environment not set error when I type cmake . in the visual studio command line so how do i set the path environment variables correctly?

**Comment by mupfdev** [comment]
1. Create a new environment variable called NGAGESDK
2. Set it to C:/ngage-toolchain
3. Open Visual Studio
4. Open folder -> select the setup sub-directory
5. Build project

**Comment by NeoGeoFreak2004** [comment]
thanks, but i have another problem when i run the program with the cmake option on visual studio 2022. it tells me this message: The environment variable NGAGESDK needs to be defined. i know how to set it i think i tried to set it by setting the path enviorment variable to the zipped master version but when i try to run it using the cmake option on visual studio 2022 it seems to me it isnt working for me , idk what to do at this point.

**Comment by mupfdev** [comment]
I just explained how to set it.

**Comment by mupfdev** [comment]
In addition you need to add this to your actual PATH variable:

%NGAGESDK%\sdk\6.1\Shared\EPOC32\gcc\bin

**Comment by NeoGeoFreak2004** [comment]
Thank you, but when I right click and press the build option it goes smoothly but then it gives me another error message. the error says:CMake Error at C:/ngage-toolchain/setup/out/build/Release/EKA2L1-prefix/src/EKA2L1-stamp/download-EKA2L1.cmake:170 (message):
    Each download failed! idk what this means so can you help me please.
