### ISSUE TITLE
Document installation for all platforms

### ISSUE THREAD

**Issue by mardab** [ngagesdk/ngage-toolchain#7]
Right now README.md suggests that this is a Windows-only solution, based on mentions of reliance on Cygwin and Visual Studio, while I was able to build under Linux just by setting `NGAGESDK`, then executing `cd setup && cmake . && make`. Please reword that document, so that some *nix-based developers don't get scared away by notion that this can only be built on Windows.

**Comment by NeoGeoFreak2004** [comment]
That's cool, so how do i set the environment for the ngagesdk on ubuntu?

**Comment by mupfdev** [comment]
It is no problem to run the setup, but it only downloads the original Symbian SDK and unpacks it to the right place.
However, the compiler only runs on Windows.

I have just opened a related issue: #9

**Comment by mupfdev** [comment]
Will be updated as soon multiple platforms are fully supported.
